### ISSUE TITLE
Setup continuous integration testing with system such as Travis

### ISSUE THREAD

**Issue by wd15** [materialsinnovation/pymks#101]

**Comment by davidbrough1** [comment]
We should add a test to the Travis matrix to continually test against the development version of sci-kit learn.

Here's an example where Pandas is continuously testing against the development version of Numpy.

https://github.com/pydata/pandas/blob/master/ci/install-3.5_NUMPY_DEV.sh

**Comment by wd15** [comment]
@davidbrough1, I'm working on this now...

**Comment by wd15** [comment]
@davidbrough1, I'm going to have to push to master and merge back into develop to get this to work. That means I'll be doing this without pull requests. Going forward we can edit the .travis.yml with pull requests once it's working correctly on master.

**Comment by wd15** [comment]
pymks uses travis now
