### ISSUE TITLE
Persistent filter kernel caching

### ISSUE THREAD

**Issue by wd15** [materialsinnovation/pymks#110]
Build a method in the Filter class for caching coefficients. Currently, pickling the model works, see https://gist.github.com/wd15/9898f39d8884f9d1f922. However, this is not very persistent. 

Caching coefficients is useful since not all calibration is fast. The interface should probably look like
```python
my_filter.cache_coeff(fileobject or filename)
```
and then with a newly instantiated filter
```python
new_filter = Filter(coefficents or filename or fileobject)
mks_regression_model = MKSRegressionModel(basis)
mks_regression_model.filter = new_filter
mks_regression_model.predict(...)
```
Not sure exactly how this should work. Need some good storage, probably use pandas and then dump to h5.

**Comment by davidbrough1** [comment]
Functionality to replace the kernel was added in PR #276.
