### ISSUE TITLE
Problem with sfepy

### ISSUE THREAD

**Issue by awhite40** [materialsinnovation/pymks#140]
In trying out some of the pyMKS examples, I get an error that says: "No module named sfepy.base.goptions"  This seems to happen when I try to use functions related to FEA such as make_elastic_FE_strain_delta.  I am attaching a screenshot of the error explanation.  I had previously cloned and installed sfepy following the installation instructions on the pyMKS website but had errors
![screenshot 2015-01-14 14 40 05](https://cloud.githubusercontent.com/assets/7670625/5746084/4ea14ec6-9bfb-11e4-8562-13fe550833bd.png)
![screenshot 2015-01-14 14 06 48](https://cloud.githubusercontent.com/assets/7670625/5746096/61155fb6-9bfb-11e4-9382-e8b92cf2eded.png)

**Comment by davidbrough1** [comment]
Try and install gcc with these directions.

http://gcc-python-plugin.readthedocs.org/en/latest/basics.html

**Comment by awhite40** [comment]
I tried using that but now can't get it to install.  it says that there is no command "make" when I try to follow the directions to build the code.

**Comment by wd15** [comment]
On Fri, Jan 16, 2015 at 9:18 AM, Alicia White <notifications@github.com>
wrote:

> I tried using that but now can't get it to install. it says that there is
> no command "make" when I try to follow the directions to build the code.
>
Hi @awhite40,

I helped develop PyMKS and I'd like to make sure that you can get things
setup right. First question: are you using Anaconda?

I assume you are trying this on Windows. Unfortunately, I haven't tried
installing Sfepy on Windows yet, but I'm sure it is a tractable problem.

Second question: can you import PyMKS? If you go to a Python prompt can you
type "import pymks" without any issues?

Third question: can you run the PyMKS tests? Use "import pymks;
pymks.test()".

If Sfepy is not installed, the tests should run, but you will get some
errors.

Once this is all working satisfactorily then we can worry about Sfepy. Can
you paste all the text (don't use an image, just the text) from the "python
setup.py install" command in the Sfepy base directory?

Thanks.

-- 
Daniel Wheeler

**Comment by awhite40** [comment]
Yes I am using anaconda.  David has sfepy working on his machine.  I can import PyMKS without any issues.  It runs the tests and says 8 errors and 3 failures and they all seem to be related to FE simulations.

Here is the error text after I try to run the install:

Missing optional package "mayavi"; you may get run-time errors
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building library "sfepy_common" sources
building library "sfepy_terms" sources
building extension "sfepy.discrete.fem.extmods._fmfield" sources
building extension "sfepy.discrete.fem.extmods.mappings" sources
building extension "sfepy.discrete.fem.extmods.assemble" sources
building extension "sfepy.discrete.fem.extmods.bases" sources
building extension "sfepy.discrete.fem.extmods.cmesh" sources
building extension "sfepy.discrete.fem.extmods.lobatto_bases" sources
building extension "sfepy.discrete.fem.extmods._geommech" sources
building extension "sfepy.discrete.iga.extmods.igac" sources
building extension "sfepy.linalg.extmods.crcm" sources
building extension "sfepy.terms.extmods.terms" sources
building data_files sources
build_src: building npy-pkg config files
running build_py
running build_clib
Looking for python27.dll
Cannot build msvcr library: "msvcr90d.dll" not found
customize Mingw32CCompiler
customize Mingw32CCompiler using build_clib
running build_ext
Looking for python27.dll
Cannot build msvcr library: "msvcr90d.dll" not found
customize Mingw32CCompiler
customize Mingw32CCompiler using build_ext
extending extension 'sfepy.discrete.fem.extmods._fmfield' defined_macros with [('__SDIR__', '\'"sfepy\\discrete\\fem\\extmods"\''),
('SFEPY_PLATFORM', 1)]
extending extension 'sfepy.discrete.fem.extmods.mappings' defined_macros with [('__SDIR__', '\'"sfepy\\discrete\\fem\\extmods"\''),
('SFEPY_PLATFORM', 1)]
extending extension 'sfepy.discrete.fem.extmods.bases' defined_macros with [('__SDIR__', '\'"sfepy\\discrete\\fem\\extmods"\''), ('S
FEPY_PLATFORM', 1)]
extending extension 'sfepy.discrete.fem.extmods.lobatto_bases' defined_macros with [('__SDIR__', '\'"sfepy\\discrete\\fem\\extmods"\
''), ('SFEPY_PLATFORM', 1)]
extending extension 'sfepy.discrete.fem.extmods._geommech' defined_macros with [('__SDIR__', '\'"sfepy\\discrete\\fem\\extmods"\''),
 ('SFEPY_PLATFORM', 1)]
extending extension 'sfepy.terms.extmods.terms' defined_macros with [('__SDIR__', '\'"sfepy\\terms\\extmods"\''), ('SFEPY_PLATFORM',
 1), ('__SDIR__', '\'"sfepy\\discrete\\fem\\extmods"\'')]
building 'sfepy.discrete.fem.extmods._fmfield' extension
compiling C sources
C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

compile options: '-D__SDIR__='"sfepy\discrete\fem\extmods"' -DSFEPY_PLATFORM=1 -D__SDIR__='"sfepy\discrete\fem\extmods"' -DSFEPY_PLA
TFORM=1 -DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Isfepy\discrete\fem\extmods -IC:\Users\awhite40\AppData\Local\Cont
inuum\Anaconda\lib\site-packages\numpy\core\include -IC:\Users\awhite40\AppData\Local\Continuum\Anaconda\include -IC:\Users\awhite40
\AppData\Local\Continuum\Anaconda\PC -c'
extra options: '-g -O2'
gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -D__SDIR__='"sfepy\discrete\fem\extmods"' -DSFEPY_PLATFORM=1 -D__SDIR__='"sf
epy\discrete\fem\extmods"' -DSFEPY_PLATFORM=1 -DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Isfepy\discrete\fem\extmods
-IC:\Users\awhite40\AppData\Local\Continuum\Anaconda\lib\site-packages\numpy\core\include -IC:\Users\awhite40\AppData\Local\Continuu
m\Anaconda\include -IC:\Users\awhite40\AppData\Local\Continuum\Anaconda\PC -c build\src.win-amd64-2.7\sfepy\discrete\fem\extmods\_fm
field.c -o build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\sfepy\discrete\fem\extmods\_fmfield.o -g -O2
Found executable C:\Program Files (x86)\CodeBlocks\MinGW\bin\gcc.exe
gcc -g -shared build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\sfepy\discrete\fem\extmods\_fmfield.o -LC:\Users\awhite40\Ap
pData\Local\Continuum\Anaconda\libs -LC:\Users\awhite40\AppData\Local\Continuum\Anaconda\PCbuild\amd64 -Lbuild\temp.win-amd64-2.7 -l
sfepy_common -lpython27 -lmsvcr90 -o build\lib.win-amd64-2.7\sfepy\discrete\fem\extmods\_fmfield.pyd
build\temp.win-amd64-2.7/libsfepy_common.a: could not read symbols: Archive has no index; run ranlib to add one
collect2.exe: error: ld returned 1 exit status
error: Command "gcc -g -shared build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\sfepy\discrete\fem\extmods\_fmfield.o -LC:\Users\awhite40\AppData\Local\Continuum\Anaconda\libs -LC:\Users\awhite40\AppData\Local\Continuum\Anaconda\PCbuild\amd64 -Lbuild\temp.
win-amd64-2.7 -lsfepy_common -lpython27 -lmsvcr90 -o build\lib.win-amd64-.7\sfepy\discrete\fem\extmods\_fmfield.pyd" failed with exit status 1

**Comment by wd15** [comment]
Hi Alicia,

Sorry for the slow reply.

What command did you use? Can you try

     $ python setup.py build_ext --inplace --compiler=mingw32

and then do the install. It probably won't make a difference, but worth a shot.


On Fri, Jan 16, 2015 at 12:24 PM, Alicia White <notifications@github.com> wrote:
> Yes I am using anaconda. David has sfepy working on his machine. I can
> import PyMKS without any issues. It runs the tests and says 8 errors and 3
> failures and they all seem to be related to FE simulations.
>
> Here is the error text after I try to run the install:
>
> Missing optional package "mayavi"; you may get run-time errors
> running install
> running build
> running config_cc
> unifing config_cc, config, build_clib, build_ext, build commands --compiler
> options
> running config_fc
> unifing config_fc, config, build_clib, build_ext, build commands --fcompiler
> options
> running build_src
> build_src
> building library "sfepy_common" sources
> building library "sfepy_terms" sources
> building extension "sfepy.discrete.fem.extmods.fmfield" sources
> building extension "sfepy.discrete.fem.extmods.mappings" sources
> building extension "sfepy.discrete.fem.extmods.assemble" sources
> building extension "sfepy.discrete.fem.extmods.bases" sources
> building extension "sfepy.discrete.fem.extmods.cmesh" sources
> building extension "sfepy.discrete.fem.extmods.lobatto_bases" sources
> building extension "sfepy.discrete.fem.extmods.geommech" sources
> building extension "sfepy.discrete.iga.extmods.igac" sources
> building extension "sfepy.linalg.extmods.crcm" sources
> building extension "sfepy.terms.extmods.terms" sources
> building data_files sources
> build_src: building npy-pkg config files
> running build_py
> running build_clib
> Looking for python27.dll
> Cannot build msvcr library: "msvcr90d.dll" not found
> customize Mingw32CCompiler
> customize Mingw32CCompiler using build_clib
> running build_ext
> Looking for python27.dll
> Cannot build msvcr library: "msvcr90d.dll" not found
> customize Mingw32CCompiler
> customize Mingw32CCompiler using build_ext
> extending extension 'sfepy.discrete.fem.extmods._fmfield' defined_macros
> with [('__SDIR', '\'"sfepy\discrete\fem\extmods"\''),
> ('SFEPY_PLATFORM', 1)]
> extending extension 'sfepy.discrete.fem.extmods.mappings' defined_macros
> with [('SDIR', '\'"sfepy\discrete\fem\extmods"\''),
> ('SFEPY_PLATFORM', 1)]
> extending extension 'sfepy.discrete.fem.extmods.bases' defined_macros with
> [('SDIR', '\'"sfepy\discrete\fem\extmods"\''), ('S
> FEPY_PLATFORM', 1)]
> extending extension 'sfepy.discrete.fem.extmods.lobatto_bases'
> defined_macros with [('SDIR', '\'"sfepy\discrete\fem\extmods"\
> ''), ('SFEPY_PLATFORM', 1)]
> extending extension 'sfepy.discrete.fem.extmods.geommech' defined_macros
> with [('__SDIR_', '\'"sfepy\discrete\fem\extmods"\''),
> ('SFEPY_PLATFORM', 1)]
> extending extension 'sfepy.terms.extmods.terms' defined_macros with
> [('SDIR', '\'"sfepy\terms\extmods"\''), ('SFEPY_PLATFORM',
> 1), ('SDIR', '\'"sfepy\discrete\fem\extmods"\'')]
> building 'sfepy.discrete.fem.extmods._fmfield' extension
> compiling C sources
> C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
>
> compile options: '-D__SDIR__='"sfepy\discrete\fem\extmods"'
> -DSFEPY_PLATFORM=1 -D__SDIR__='"sfepy\discrete\fem\extmods"' -DSFEPY_PLA
> TFORM=1 -DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900
> -Isfepy\discrete\fem\extmods -IC:\Users\awhite40\AppData\Local\Cont
> inuum\Anaconda\lib\site-packages\numpy\core\include
> -IC:\Users\awhite40\AppData\Local\Continuum\Anaconda\include
> -IC:\Users\awhite40
> \AppData\Local\Continuum\Anaconda\PC -c'
> extra options: '-g -O2'
> gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
> -D__SDIR__='"sfepy\discrete\fem\extmods"' -DSFEPY_PLATFORM=1 -D__SDIR__='"sf
> epy\discrete\fem\extmods"' -DSFEPY_PLATFORM=1 -DNPY_MINGW_USE_CUSTOM_MSVCR
> -D__MSVCRT_VERSION__=0x0900 -Isfepy\discrete\fem\extmods
> -IC:\Users\awhite40\AppData\Local\Continuum\Anaconda\lib\site-packages\numpy\core\include
> -IC:\Users\awhite40\AppData\Local\Continuu
> m\Anaconda\include -IC:\Users\awhite40\AppData\Local\Continuum\Anaconda\PC
> -c build\src.win-amd64-2.7\sfepy\discrete\fem\extmods_fm
> field.c -o
> build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\sfepy\discrete\fem\extmods_fmfield.o
> -g -O2
> Found executable C:\Program Files (x86)\CodeBlocks\MinGW\bin\gcc.exe
> gcc -g -shared
> build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\sfepy\discrete\fem\extmods_fmfield.o
> -LC:\Users\awhite40\Ap
> pData\Local\Continuum\Anaconda\libs
> -LC:\Users\awhite40\AppData\Local\Continuum\Anaconda\PCbuild\amd64
> -Lbuild\temp.win-amd64-2.7 -l
> sfepy_common -lpython27 -lmsvcr90 -o
> build\lib.win-amd64-2.7\sfepy\discrete\fem\extmods_fmfield.pyd
> build\temp.win-amd64-2.7/libsfepy_common.a: could not read symbols: Archive
> has no index; run ranlib to add one
> collect2.exe: error: ld returned 1 exit status
> error: Command "gcc -g -shared
> build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\sfepy\discrete\fem\extmods_fmfield.o
> -LC:\Users\awhite40\AppData\Local\Continuum\Anaconda\libs
> -LC:\Users\awhite40\AppData\Local\Continuum\Anaconda\PCbuild\amd64
> -Lbuild\temp.
> win-amd64-2.7 -lsfepy_common -lpython27 -lmsvcr90 -o
> build\lib.win-amd64-.7\sfepy\discrete\fem\extmods_fmfield.pyd" failed with
> exit status 1
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Daniel Wheeler

**Comment by awhite40** [comment]
I have tried using that command and it gave me the same result.  
As for the instructions, I have looked at those but I am not sure what I would need to install.  Python(x,y) seems to be an alternate to anaconda but does it have packages that I might need that anaconda doesn't?  I did try installing  umfpackpy from the instructions and it seemed to install but didn't affect the errors I am getting.  I have also sent a message through the mailing list asking for help.

**Comment by wd15** [comment]
On Wed, Jan 21, 2015 at 10:05 AM, Alicia White <notifications@github.com>
wrote:

> I have tried using that command and it gave me the same result.
>
> As for the instructions, I have looked at those but I am not sure what I
> would need to install. Python(x,y) seems to be an alternate to anaconda but
> does it have packages that I might need that anaconda doesn't? I did try
> installing umfpackpy from the instructions and it seemed to install but
> didn't affect the errors I am getting. I have also sent a message through
> the mailing list asking for help.
>
Did you email the "sfepy-devel" google groups mailing list? I subscribe to
that list and your mail doesn't seem to be on there.

   https://groups.google.com/forum/#!forum/sfepy-devel

You will very likely get the help you need on that list.

Thanks for following up on this, getting Sfepy working on Windows is very
important for the PyMKS project.

-- 
Daniel Wheeler

**Comment by awhite40** [comment]
So I am still not sure why it wasn't working but after uninstalling and reinstalling anaconda, I reinstalled  sfepy and pymks and they now seem to be working perfectly.

**Comment by wd15** [comment]
Awesome that it works. I'm sorry that it has been such a struggle. Could we
update the installation instructions in some way for Windows users?

On Thu, Feb 5, 2015 at 2:41 PM, Alicia White <notifications@github.com>
wrote:

> Closed #140 <https://github.com/materialsinnovation/pymks/issues/140>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/materialsinnovation/pymks/issues/140#event-231007458>.
>



-- 
Daniel Wheeler

**Comment by davidbrough1** [comment]
We should add some Windows installation documentation for PyMKS.

Should we ask SfePy to add installation documentation for Windows using
Anaconda?

Thanks,

David

**Comment by wd15** [comment]
On Fri, Feb 6, 2015 at 10:42 AM, David Brough <notifications@github.com>
wrote:

> We should add some Windows installation documentation for PyMKS.
>
> Should we ask SfePy to add installation documentation for Windows using
> Anaconda?
>

If we have a clear set of instructions ourselves, maybe we should submit a
pull request to Sfepy. Maybe wait until the subject comes up again. You can
spend too much time on this sort of stuff.

-- 
Daniel Wheeler

**Comment by NACH-2021** [comment]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-19-4088b751c989> in <module>
      1 import pymks
----> 2 from pymks_share import DataManager
      3 import numpy as np

C:\code\lib\site-packages\pymks_share\__init__.py in <module>
----> 1 from data_manager import DataManager
      2 
      3 
      4 def get_version():
      5     from pkg_resources import get_distribution, DistributionNotFound

ModuleNotFoundError: No module named 'data_manager'

**Comment by wd15** [comment]
> ## How i can solve this error :
> 
> ModuleNotFoundError Traceback (most recent call last)
> in
> 1 import pymks
> ----> 2 from pymks_share import DataManager

This is from an older version of PyMKS. Use the latest version if possible.
