### ISSUE TITLE
Sfepy issue: 'Problem' object has no attribute 'set_solvers_instances'

### ISSUE THREAD

**Issue by wd15** [materialsinnovation/pymks#161]
See https://gist.github.com/callmeskywalker/81960735cf413c1ef9d6

**Comment by davidbrough1** [comment]
Looks like the API for SfePy was changed.

https://github.com/sfepy/sfepy/commit/a809c423691962dc56a33deff5cb96704e1938a5

**Comment by davidbrough1** [comment]
Fix #164
