### ISSUE TITLE
Update reduced data name

### ISSUE THREAD

**Issue by davidbrough1** [materialsinnovation/pymks#200]
change preduced_predict_data to reduced_predict_data

**Comment by callmeskywalker** [comment]
Just out of curiosity how could I go about helping with something like this? Is there a good way to search for this function in the repository? 

I found my way to *pymks* from *fipy* and interests in image processing. I still have not quite wrapped my head around what the Materials Knowledge System does and is used for, but I am curious to learn.

**Comment by davidbrough1** [comment]
@callmeskywalker If you are interested in helping with PyMKS please try and fix some of the small issues and submit pull requests. We would love to have you contribute to the project. For this issue, I am referring to the MKSHomogenizationModel documention

https://github.com/materialsinnovation/pymks/blob/master/pymks/mks_homogenization_model.py#L29

**Comment by callmeskywalker** [comment]
Is a fix for something like this as simple as changing that one line and then submitting the pull request? Or will there be some tracing through that file and others perhaps, where the variable needs to be changed? I guess it's just one particular instance because it is labeled as a typo.

**Comment by davidbrough1** [comment]
In this case because the only change is made to the documentation we just
need to fix this one section.

If a change is made to code we would need to run the tests to maks sure we
haven't broken anything else.

Also if you create pull request please follow the following procedure.

https://github.com/materialsinnovation/pymks/blob/master/ADMINISTRATA.md

**Comment by callmeskywalker** [comment]
I think I have correctly updated my fork of pymks, which I did by:
    
    git fetch upstream
    git merge upstream/master

My git repository is configured on my machine as:
    
    git remote -v
----
    origin  https://github.com/callmeskywalker/pymks.git (fetch)
    origin  https://github.com/callmeskywalker/pymks.git (push)
    upstream  https://github.com/materialsinnovation/pymks.git (fetch)
    upstream  https://github.com/materialsinnovation/pymks.git (push)

I fixed the typo #200 , so now:

    git status
----
    On branch master
    Your branch is ahead of 'origin/master' by 239 commits.
      (use "git push" to publish your local commits)

    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

	    modified:   mks_homogenization_model.py

    Untracked files:
      (use "git add <file>..." to include in what will be committed)

	    ../regions.vtk

    no changes added to commit (use "git add" and/or "git commit -a")

I do not understand what the `Untracked files` are (perhaps something to be cautious of).
I am thinking that I will just `git add mks_homogenization_model.py`.

Then commit `git commit ` using this format:

    # Header, 50 characters or less
    # fixed #200
    # Links to tickets, fixes etc
    # (what link do I put here)?
    # Main Message
    # fixed the typo/updated preduce to reduce
    # List of other changes
    # 
    # Answer the following questions:
    #
    #   * Why is this change necessary?
    # there was a typo/update needed in documentation  
    #   * How does it address the issue?
    # changes the typo
    #   * What side effects does this change have?
    # no side effects

Assuming what I have done is correct, how do I go about pushing for code review?
Obviously there is not really any code to review or testing in this case.
Well please let me know if any of this is wrong.
Further advice and comments are appreciated. Thanks!

**Comment by davidbrough1** [comment]
The overall process you mentioned is correct. The untracked files are
created during the tests, and should not be committed (another issue should
be create to fix this).

The only thing I would change is to have your changes on a new branch
checkout from an updated develop branch with a name that has the issue
nunber and some description related to the issue in the format outlined in
the administrata.

https://github.com/materialsinnovation/pymks/blob/master/ADMINISTRATA.md#branching

Once you are ready to have your changes reviewed and merged, submit a pull
request to upstream develop branch.
https://help.github.com/articles/using-pull-requests/#initiating-the-pull-request

I think I have correctly updated my fork of pymks, which I did by:

git fetch upstream
git merge upstream/master

My git repository is configured on my machine as:

git remote -v

------------------------------

origin  https://github.com/callmeskywalker/pymks.git (fetch)
origin  https://github.com/callmeskywalker/pymks.git (push)
upstream  https://github.com/materialsinnovation/pymks.git (fetch)
upstream  https://github.com/materialsinnovation/pymks.git (push)

I fixed the typo #200
<https://github.com/materialsinnovation/pymks/issues/200> , so now:

git status

------------------------------

On branch master
Your branch is ahead of 'origin/master' by 239 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   mks_homogenization_model.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)

    ../regions.vtk

no changes added to commit (use "git add" and/or "git commit -a")

I do not understand what the Untracked files are (perhaps something to be
cautious of).
I am thinking that I will just git add mks_homogenization_model.py.

Then commit git commit using this format:

# Header, 50 characters or less
# fixed #200
# Links to tickets, fixes etc
# (what link do I put here)?
# Main Message
# fixed the typo/updated preduce to reduce
# List of other changes
#
# Answer the following questions:
#
#   * Why is this change necessary?
# there was a typo/update needed in documentation
#   * How does it address the issue?
# changes the typo
#   * What side effects does this change have?
# no side effects

Assuming what I have done is correct, how do I go about pushing for code
review?
Obviously there is not really any code to review or testing in this case.
Well please let me know if any of this is wrong.
Further advice and comments are appreciated. Thanks!

—
Reply to this email directly or view it on GitHub
<https://github.com/materialsinnovation/pymks/issues/200#issuecomment-130771622>
.

**Comment by callmeskywalker** [comment]
So I make a branch from [here] (https://github.com/materialsinnovation/pymks/tree/develop) and push from my branch to back to that one. I think I understand correctly now. Thanks for the help!

**Comment by callmeskywalker** [comment]
Should I go with the `gh-pages` branch or the `develop` branch? I'm thinking its likely `develop`. But that is kind of a guess.

**Comment by davidbrough1** [comment]
Develop branch.
2015/8/13 下午7:07於 "Kyle Lawlor" <notifications@github.com>寫道：
