### ISSUE TITLE
link to requirements.md in installation.md does not work

### ISSUE THREAD

**Issue by callmeskywalker** [materialsinnovation/pymks#213]
This link is getting a 404 error (at least for me)
https://github.com/materialsinnovation/pymks/blob/master/INSTALLATION.md#requirements
Here is the link to that file:
https://github.com/materialsinnovation/pymks/blob/master/REQUIREMENTS.md
I guess the link probably just needs to be changed in INSTALLATION.md

**Comment by callmeskywalker** [comment]
Not sure how to close this now that the link is working, do I have to issue a comment something like `PR xxx` before closing? That seems to be the format. I am not sure how to find which PR fixes this.

**Comment by davidbrough1** [comment]
This link needs to point to REQUIREMENTS.html while building the documentation using sphinx, 

http://materialsinnovation.github.io/pymks/rst/INSTALLATION.html#requirements,

but needs to link to REQUIREMENTS.md on the master branch. 

https://github.com/materialsinnovation/pymks/blob/master/INSTALLATION.md#requirements

When a new version of PyMKS is released this link will need to be changed to point to REQUIREMENTS.md on the master branch. No pull request (PR) is need to fix this issue.
