### ISSUE TITLE
Move tests in tools from doc

### ISSUE THREAD

**Issue by davidbrough1** [materialsinnovation/pymks#225]
Move tests from `tools.py` to the `test` directory to remove the dependance on `matplotlib` to pass the tests.

**Comment by davidbrough1** [comment]
As an example the doc test found in `_get_ticks_params` 

https://github.com/materialsinnovation/pymks/blob/master/pymks/tools.py#L659

should be moved to a new file in the `tests` directory.

https://github.com/materialsinnovation/pymks/tree/master/pymks/tests

**Comment by wd15** [comment]
Matplotlib is no longer required to run the tests.
