### ISSUE TITLE
Generate conda builds for Windows and Mac OS X

### ISSUE THREAD

**Issue by wd15** [materialsinnovation/pymks#294]

**Comment by ahmetcecen** [comment]
Let me know if you need help on the Windows side. The plan is to further incorporate the Conda call and an environment creation into the current somewhat defunct Windows Installer eventually.

**Comment by davidbrough1** [comment]
@saganaut, would you be willing to help with the Mac OS X build?

**Comment by wd15** [comment]
Now on conda-forge so this is dealt with
