### ISSUE TITLE
Basis set for pre-segmented data

### ISSUE THREAD

**Issue by ajmedford** [materialsinnovation/pymks#298]
In pyMKS 0.2 it was easy to do 2pt stats on pre-segmented data, since the "discretize" call happened outside of the "correlate" function. It looks like a more sophisticated approach has been used in pyMKS 0.3, likely to account for indexed (non-scalar) data like the Euler angles for the GSH basis. However, in the event that you have pre-segmented data, it is now unclear how to work with it.

To fix this it should be relatively easy to create a "DummyBasis" or "PreSegmentedBasis" that assumes the input data is already discretized. It could perhaps take another basis class as an optional argument (e.g. GSH) to account for non-scalar data.

**Comment by wd15** [comment]
Closing as this is more than two years old
