### ISSUE TITLE
pyfftw Bug

### ISSUE THREAD

**Issue by davidbrough1** [materialsinnovation/pymks#304]
Depending on the order in which numpy and pyfftw are imported, a `RuntimeError` can be raised.

https://github.com/pyFFTW/pyFFTW/issues/106#issuecomment-218342768

**Comment by wd15** [comment]
@davidbrough1, is there a workaround for us to fix this issue? Just by changing the import order? If so maybe I should do that in #303 and resubmit the pull request.

**Comment by davidbrough1** [comment]
The following sequence import statements seems to work for all operating systems and python environments.

    import pymks
    import numpy

There is an issue with numpy using anaconda's MKL and pyfftw. The pyfftw development team recommends that anaconda users not on Windows install pyfftw using the following.

    conda install -c conda-forge pyfftw

https://github.com/pyFFTW/pyFFTW/issues/40#issuecomment-225401625

**Comment by wd15** [comment]
@davidbrough1, I wasn't seeing the same errors as you as I was using the conda-forge channel to install pyfftw.
