### ISSUE TITLE
nosetests missing from conda package requirements

### ISSUE THREAD

**Issue by doronator** [materialsinnovation/pymks#332]
Hey folks,
Great job with this interesting new approach to materials design - combinig it with data science. I like!

Looks to me like nosetests should be included in the meta.yaml
for the conda package. I followed these steps on a mac osx, and the tests failed on not finding nose...

(1) I created an empty conda environment, and switch to it
```
> conda create --name pymks_env
> source activate pymks_env
```
(2) Install sfepy (for mac os x this needed a different source than pymks)
`> conda install -c conda-forge sfepy`
(3) install pymks:
```
> conda config --add channels pymks
> conda install pymks
```
(4) run the tests:
`> python -c "import pymks; pymks.test()"`

What one gets in the output is:
```

python -c "import pymks; pymks.test()"
=========================================== test session starts ============================================
platform darwin -- Python 2.7.12, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /Users/doron, inifile:
collected 95 items / 2 errors

================================================== ERRORS ==================================================
 ERROR collecting anaconda/envs/pymks_env/lib/python2.7/site-packages/pymks/tests/test_microstructure_generator.py
anaconda/envs/pymks_env/lib/python2.7/site-packages/pymks/tests/test_microstructure_generator.py:1: in <module>
    from nose.tools import raises
E   ImportError: No module named nose.tools
 ERROR collecting anaconda/envs/pymks_env/lib/python2.7/site-packages/pymks/tests/test_microstructure_generator.py
ImportError while importing test module '/Users/doron/anaconda/envs/pymks_env/lib/python2.7/site-packages/pymks/tests/test_microstructure_generator.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
anaconda/envs/pymks_env/lib/python2.7/site-packages/pymks/tests/test_microstructure_generator.py:1: in <module>
    from nose.tools import raises
E   ImportError: No module named nose.tools
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================= 2 error in 2.55 seconds ==========================================
```

I think the fix can be as simple as adding "nose" to the following section in meta.yaml:

```
requirements:
  build:
```

**Comment by wd15** [comment]
@doronator, thanks for the feedback. We will try and look into this in the near future.

**Comment by wd15** [comment]
@doronator, the next release of PyMKS will  not be using Nosetest at all, we've switched to using Pytest. This is now on the develop branch of PyMKS, https://github.com/materialsinnovation/pymks/blob/develop/.travis.yml#L41.

Also, we hope to have a Conda-forge release of PyMKS is the near future so we will be removing the pymks channel altogether at that point.

Nonetheless, thanks for your feedback.
