### ISSUE TITLE
Scipy versions 1.x.y are broken with PyMKS

### ISSUE THREAD

**Issue by wd15** [materialsinnovation/pymks#345]
`fourier_gaussian` appears the be broken in Scipy 1.x.y.  The following seems to break,

https://github.com/materialsinnovation/pymks/blob/master/pymks/datasets/microstructure_generator.py#L41

For example,
```
fourier_gaussian(np.ones([3,3]), 1)
```
returns
```
[[5.26354425e-315 5.13029228e-315 5.13029228e-315]
 [5.13029228e-315 4.99799940e-315 4.99799940e-315]
 [5.13029228e-315 4.99799940e-315 4.99799940e-315]]
```
which is wrong

**Comment by wd15** [comment]
Filed a Scipy bug for this one: https://github.com/scipy/scipy/issues/8747

**Comment by rgommers** [comment]
With newest SciPy:
```
In [16]: fourier_gaussian(np.ones([3,3]), 1)                                          
Out[16]: 
array([[1.        , 0.11155412, 0.11155412],
       [0.11155412, 0.01244432, 0.01244432],
       [0.11155412, 0.01244432, 0.01244432]])
```

**Comment by wd15** [comment]
@rgommers, thanks so much for pointing this out, much appreciated. We have [updated the PyMKS build](https://github.com/materialsinnovation/pymks/pulls) accordingly.
