### ISSUE TITLE
Sfepy broken in latest version, 2018.4

### ISSUE THREAD

**Issue by wd15** [materialsinnovation/pymks#346]
Get the following error,

```
pb = Problem('elasticity', equations=eqs, auto_solvers=None)
TypeError: __init__() got an unexpected keyword argument 'auto_solvers'
```

**Comment by erik-tastepe** [comment]
Hi, I'm getting this same issue and am unable to follow along with the notebook examples. Is there a solution to this?

**Comment by wd15** [comment]
@erik-tastepe, yes, the solution is to use version `2017.4.1` of Sfepy until this is resolved.

I recently created a Nix recipe for PyMKS that uses specific versions for dependencies, see https://github.com/materialsinnovation/pymks/blob/develop/default.nix and https://github.com/materialsinnovation/pymks/blob/develop/INSTALLATION.md#nix.

**Comment by wd15** [comment]
@erik-tastepe, there is now a fix for this on develop. See these [changes](https://github.com/materialsinnovation/pymks/commit/1ad1b93d17339274ee3f89380d4bfc852d15a13d).
