### ISSUE TITLE
Update readthedocs

### ISSUE THREAD

**Issue by auag92** [materialsinnovation/pymks#367]
Modify Readthedocs to include pymks/fmks and see the rendering of the develop branch is correct.

Stuff that needs to be done before release:

 - [x] ensure docs build on readthedocs
 - [x] clean up readme 
   - [x] link to installation and theory guides
   - [x] correct citation
   - [x] remove some badges
   - [x] more narrative about using PyMKS
   - [x] link to API
  - [x] fix up installation guide
    - [x] remove conda-forge and pip until it acutally works
  - [x] fix up API
    - [x] imporove API formatting - currently broken
    - [x] include contents left side bar for API??
  - [x] remove pointless rst files that aren't part of the documentation

Future:
 
 - [ ] much more explanation about functions and classes and how to use them
 - [ ] cross reference from API to notebooks and visa-versa
 - [ ] reformat to more standard sphinx theme with left side bars contents
 - [ ] improve narrative about PyMKS and make it easier to navigate

**Comment by wd15** [comment]
keep open
