### ISSUE TITLE
GSH basis requires 3 angles as states

### ISSUE THREAD

**Issue by SvenPVoigt** [materialsinnovation/pymks#372]
The GSH basis class requires 3 angles when the check function is called. However, this is only the case for 3D samples. Samples such as certain types of thin films may have two constrained angles and the microstructure only changes in one angle.

Additionally, I am not even sure this class should be restricted to angles. Theoretically, any continuous variable should be represented in the GSH bases.

**Comment by wd15** [comment]
@SvenPVoigt would you like to have a go at reimplementing the GSH basis again? It needs to be done in a more coherent way.

**Comment by SvenPVoigt** [comment]
I don't have any experience in coding the GSH basis and it isn't aligned with my current projects, but I will keep the request in mind in case I can help.
