### ISSUE TITLE
Non-determenistic behavour in stress.ipynb

### ISSUE THREAD

**Issue by wd15** [materialsinnovation/pymks#396]
The notebook stress.ipynb is currently not deterministic. This may be related to an earlier problem that occurred after updating the Sklearn / Numpy stack in the Nix recipe. The earlier problem was to do with a Numpy dot product having parts of the array being overwritten with the wrong values (probably a memory issue to do with the Numpy / blas interaction). This problem occurred in Sklearn's PCA, which is where it is occurring now.

How to diagnose this?

 - [ ] check that a conda installation works
 - [x] check that the nix install works with a `.local` installation of numpy
 - [ ] once we have a working version, then try to create a small example with just a few samples on a small grid. See if we can take those numbers and use them just with Numpy to create a debug test case to pass to either Nixpkgs or Numpy.

**Comment by beyucel** [comment]
I think we can close this one as well, what do you think, @wd15 ?

**Comment by wd15** [comment]
yes
