### ISSUE TITLE
Create bug release with new conda install command

### ISSUE THREAD

**Issue by wd15** [materialsinnovation/pymks#403]
The current documentation on the website is broken. Update to reflect conda install command that we know actually works.

    $ conda install -c conda-forge pymks scikit-learn=0.18 scipy=0.19 sfepy=2017.2

Also, matplotlib needs to be updated.

**Comment by beyucel** [comment]
I tested following conda install command and all notebooks are working on the **master** branch with this installation.

   $ conda install -c conda-forge pymks scikit-learn=0.19 sfepy=2017.2 nomkl toolz dask scipy=0.19.1 matplotlib=2.0.2

I will just create a clean environment on Windows and test it over there too.

**Comment by wd15** [comment]
We're not doing this. Let's get develop out
