### ISSUE TITLE
TwoPointcorrelation issues

### ISSUE THREAD

**Issue by wd15** [materialsinnovation/pymks#435]
- [ ] default cutoff should be the domain size
 - [ ] TwoPointcorrelation -> TwoPointCorrelation
 - [ ] returning even shaped microstructures, should be odd shaped

**Comment by wd15** [comment]
The following code breaks
```
from sklearn.pipeline import Pipeline
from pymks.fmks.bases.primitive import PrimitiveTransformer
from pymks.fmks.correlations import TwoPointcorrelation
from pymks.fmks.data.checkerboard import generate

x_data = generate((21 * 8, 21 * 8), (21, 21))

model = Pipeline(steps=[
    ('discretize', PrimitiveTransformer(n_state=2, min_=0.0, max_=1.0)),
    ('correlations', TwoPointcorrelation(periodic_boundary=False, cutoff=x_data.shape[1]))
])

x_auto = model.transform(x_data).compute()
x_auto.shape
```
with 
```
AttributeError: 'numpy.ndarray' object has no attribute 'chunks'
```

The above will only work on my https://github.com/wd15/pymks/tree/checkerboard branch. This works if `periodic_boundary=True` though

**Comment by beyucel** [comment]
We also need to add periodic boundary padder. if cutoff value > shape/2, we are having issues.
I am working on it
