### ISSUE TITLE
Add input array size information for the function arguments

### ISSUE THREAD

**Issue by beyucel** [materialsinnovation/pymks#447]
- Add input array size information for the function arguments.

This will make development and troubleshooting a lot easier.  Example: 

    """Calculate the 2-points stats for two arrays

    Args:
      arr1: array used to calculate cross-correlations (N x X x Y)
      arr2: array used to calculate cross-correlations
      periodic_boundary: whether to assume a periodic boundary (default is true)
      cutoff: the subarray of the 2 point stats to keep
      --------------------------------------------------------------------------------------------------------------
      N= number of samples
      X= microstructure vertical dimension size 
      Y= microstructure horizontal dimension size 

    Returns:
      the snipped 2-points stats

    >>> two_point_stats(
    ...     da.from_array(np.arange(10).reshape(2, 5), chunks=(2, 5)),
    ...     da.from_array(np.arange(10).reshape(2, 5), chunks=(2, 5)),
    ... ).shape
    (2, 5)

    """

**Comment by wd15** [comment]
Regarding the argument documentation, we're using the [Google style guide](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods), like [here](https://github.com/materialsinnovation/pymks/blob/master/pymks/mks_homogenization_model.py#L73). We've not always been that consistent though.
