### ISSUE TITLE
Cell 12 in stress.ipynb seems to be useless

### ISSUE THREAD

**Issue by wd15** [materialsinnovation/pymks#475]
The output from cell 12 in [stress.ipynb](https://github.com/materialsinnovation/pymks/blob/master/notebooks/stress.ipynb) isn't really showing anything useful and certainly not more useful then the following plot. I'm not going to keep it.

**Comment by beyucel** [comment]
Yes, I agree. Components between 4-9 look identical and following plot is much clear then cell 12.
