### ISSUE TITLE
"RandomizedPCA( )" has been changed

### ISSUE THREAD

**Issue by pankajarmo** [materialsinnovation/pymks#506]
RandomizePCA() was removed in an older version of SKLearn and is simply a parameter in PCA(). mks_structure_analysis.py contains  "_from sklearn. decomposition import RandomizePCA_" which needs to be changed to only "PCA". Therefore it shows error importing RandomizePCA( )
![Screenshot from 2020-08-08 03-45-07](https://user-images.githubusercontent.com/34365069/89668511-79cb9f00-d8fb-11ea-9b44-9b4f5815ed5e.png)
"

**Comment by wd15** [comment]
Thanks for filing an issue on this. However, the `MKSStructureAnalysis` is now deprecated so won't receive anymore updates. I suggest looking at master branch and checking some of the notebooks. Let us know if you need help transitioning any of your workflows to the new version of PyMKS.
