### ISSUE TITLE
No Pair Correlations

### ISSUE THREAD

**Issue by SvenPVoigt** [materialsinnovation/pymks#519]
The transformation from 2point stats to pair correlations is straightforward and used in many analyses (I may have an example dataset). Is this transformation implemented?

**Comment by wd15** [comment]
What are pair correlations?

**Comment by SvenPVoigt** [comment]
If we were to write the coordinates of spatial 2point statistics in polar coordinates, then pair correlations are 2point statistics as a function of radius only. All angles are dropped.

**Comment by wd15** [comment]
As you already have the code then please do submit a PR and I can work on with you. The PR can be pretty rough to start and we'll tidy it up.
