### ISSUE TITLE
Windows pymks installation Issue

### ISSUE THREAD

**Issue by beyucel** [materialsinnovation/pymks#520]
This happened in `intro` notebook:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-edab5e847d00> in <module>
     13 from sklearn.linear_model import LinearRegression
     14 
---> 15 from pymks import (
     16     generate_multiphase,
     17     generate_delta,

~\AppData\Roaming\Python\Python37\site-packages\pymks\__init__.py in <module>
     10 from .bases.primitive import PrimitiveBasis
     11 from .bases.legendre import LegendreBasis
---> 12 from .mks_structure_analysis import MKSStructureAnalysis
     13 from .mks_homogenization_model import MKSHomogenizationModel
     14 MKSRegressionModel = MKSLocalizationModel

~\AppData\Roaming\Python\Python37\site-packages\pymks\mks_structure_analysis.py in <module>
      1 from pymks.stats import correlate
      2 from sklearn.base import BaseEstimator
----> 3 from sklearn.decomposition import RandomizedPCA
      4 import numpy as np
      5 

ImportError: cannot import name 'RandomizedPCA' from 'sklearn.decomposition' (C:\Users\yucel\Miniconda3\envs\pymks\lib\site-packages\sklearn\decomposition\__init__.py)

**Comment by beyucel** [comment]
This is related to old pymks but still causing problems for current notebooks

**Comment by wd15** [comment]
Let's just remove the old imports from the `__init__.py`.

**Comment by beyucel** [comment]
Yes that is the issue. I mean I got the same issue with the linux conda as well. It  did not make sense tbh because it does not fail Circle CI

**Comment by wd15** [comment]
Wait, what version of PyMKS is installed? That must be with a very old version of PyMKS. It was [fixed with this change](https://github.com/materialsinnovation/pymks/commit/edae106f302355cae0fbeba932a7de6befed7842#diff-00f15c81238a412f12528392cf54e80eL3) 12 months ago.

**Comment by wd15** [comment]
@beyucel is this still an issue or was it just the wrong version of PyMKS or not installed?

**Comment by wd15** [comment]
What do you get when you print `pymks.__version__` in the notebook? It's most likely that Jupyter is installed with a different Python than the one that the latest version PyMKS is installed with. `pymks.__path__` will tell you which PyMKS you're using in the notebook.
