### ISSUE TITLE
Numpy array input issue

### ISSUE THREAD

**Issue by beyucel** [materialsinnovation/pymks#526]
Currently , `two_point_stats(arr1, arr2, mask=None, periodic_boundary=True, cutoff=None)` is our simplest function for two point stats. This only accepts dask array. 

AttributeError: 'numpy.ndarray' object has no attribute 'chunks'

**Comment by wd15** [comment]
There is a `make_da_return` function on PR #539 that will take care of this issue. The function is [here](https://github.com/materialsinnovation/pymks/pull/539/files#diff-8acdcae20431a323736b5f5c935f69d9c9c7301ffe4ad2ca23d243fed4e57f64R290). We can update `two_points_stats` once that's merged.
