### ISSUE TITLE
cutoff issue

### ISSUE THREAD

**Issue by mikepl9** [materialsinnovation/pymks#572]
Hello!
Thanks for your work.

I have been trying visualize the two-point statistics of three microstructures of my dataset.
Here is some screenshots of the relevant parts of the code.

![a](https://user-images.githubusercontent.com/69092842/175774479-16518e5e-4066-4141-bc3b-bc80f957f31d.PNG)
![b](https://user-images.githubusercontent.com/69092842/175774481-6e86e15b-8705-4add-b2ed-64047fdcd6ce.PNG)
![c](https://user-images.githubusercontent.com/69092842/175774483-b8d00b06-9980-44a3-8928-8d7578210968.PNG)
![d](https://user-images.githubusercontent.com/69092842/175774484-b0d7cd2a-7002-44a6-af7a-52f641ca93fe.PNG)

The statistics look fine for the first two, but the third is probably false.
What do you think? I believe it's a cutoff issue, but I tried picking smaller and bigger values for it (it didn't work).

The microstructures are 600x600 binary images.

Thanks a lot!

**Comment by mikepl9** [comment]
> I would expect the central pattern to be bigger, as it also gets bigger from the first microstructure to the second. 
Maybe that's not the case. But the pattern being so small looks problematic.

The three 2-point stats are for the three microstructures that I also visualize in the beginning.

Regardless, PyMKS is great.
Thanks so much!

**Comment by mikepl9** [comment]
I checked it and it is right. 
I had the last columns reversed, so it is the 1->1, as I wanted. 
If you don't mind, could you explain why the central pattern gets so small as the grains get bigger?

**Comment by wd15** [comment]
> I checked it and it is right. I had the last columns reversed, so it is the 1->1, as I wanted. If you don't mind, could you explain why the central pattern gets so small as the grains get bigger?

I'm a bit confused now, but this is what I think. In the case where the grains are large, the white to white stats should be very small as it's essentially a grain boundary that isn't oriented in any particular direction. The blue to blue stats should have a much larger central region. It depends which set of 2-point stats you're referring to (and you're saying that they were reversed). Does that make sense?
